const mod2weight = {
    "Map Bosses drop 1 additional Unique Item\n": 500,
    "Final Map Boss in each Map drops an additional Shaper Guardian Map (Tier 14+)\nMap Bosses deal 100% more Damage\nMap Bosses have 200% more Life\n": 50,
    "Final Map Boss in each Map drops an additional Elder Guardian Map (Tier 14+)\nMap Bosses deal 100% more Damage\nMap Bosses have 200% more Life\n": 50,
    "Final Map Boss in each Map drops an additional Conqueror Map\nMap Bosses deal 100% more Damage\nMap Bosses have 200% more Life\n": 50,
    "20% increased Pack Size in your Unidentified Maps\nItems found in your Identified Maps are Identified\n": 250,
    "Players and Monsters take 12% increased Fire Damage\nYour Maps contain 6 additional packs of Monsters that deal Fire Damage\n": 1000,
    "Players and Monsters take 12% increased Cold Damage\nYour Maps contain 6 additional packs of Monsters that deal Cold Damage\n": 1000,
    "Players and Monsters take 12% increased Lightning Damage\nYour Maps contain 6 additional packs of Monsters that deal Lightning Damage\n": 1000,
    "Players and Monsters take 12% increased Physical Damage\nYour Maps contain 6 additional packs of Monsters that deal Physical Damage\n": 1000,
    "Players and Monsters take 12% increased Chaos Damage\nYour Maps contain 6 additional packs of Monsters that deal Chaos Damage\n": 1000,
    "Unique Monsters drop Corrupted Items\n": 250,
    "Map Bosses deal 20% increased Damage\nYour Maps have 20% Quality\n": 500,
    "Map Bosses have 20% increased Life\nQuality bonus of your Maps also applies to Rarity of Items found\n": 500,
    "Your Maps are Alluring\n": 10,
    "Your Maps contain Einhar\n": 125,
    "Your Maps contain Alva\n": 125,
    "Your Maps contain Niko\n": 125,
    "Your Maps contain Jun\n": 125,
    "Strongboxes in your Maps are at least Rare\nStrongboxes in your Maps are Corrupted\nYour Maps contain 2 additional Strongboxes\n": 500,
    "Items found in your Maps have 5% chance to be Corrupted\nMap Bosses of your Corrupted Maps drop 2 additional Vaal Items\n": 500,
    "25% increased Magic Pack Size\n": 500,
    "Rogue Exiles deal 20% increased Damage\nRogue Exiles drop 2 additional Jewels\nRogue Exiles in your Maps have 20% increased Life\nYour Maps are inhabited by 2 additional Rogue Exiles\n": 500,
    "Your Magic Maps contain 4 additional packs of Magic Monsters\nYour Normal Maps contain 4 additional packs of Normal Monsters\nYour Rare Maps contain 4 additional Rare Monster packs\n": 1000,
    "Players and their Minions cannot take Reflected Damage\nYour Maps contain 4 additional Packs with Mirrored Rare Monsters\n": 1000,
    "Your Maps contain 25 additional Clusters of Mysterious Barrels\n": 250,
    "Strongbox Monsters are Enraged\nStrongbox Monsters have 500% increased Item Quantity\nYour Maps contain an additional Strongbox\n": 250,
    "Your Maps contain hunted traitors\n": 250,
    "Your Maps contain 6 additional packs of Monsters that Convert when Killed\n": 1000,
    "Player's Life and Mana Recovery from Flasks are instant\nYour Maps contain 6 additional packs of Monsters that Heal\n": 1000,
    "An additional Map drops on Completing your Maps\nMap Bosses are accompanied by Bodyguards\n": 250,
    "Your Maps can contain Breaches\nYour Maps contain an additional Breach\n": 250,
    "Breaches in your Maps belong to Xoph\nBreaches in your Maps contain 3 additional Clasped Hands\n": 50,
    "Breaches in your Maps belong to Tul\nBreaches in your Maps contain 3 additional Clasped Hands\n": 50,
    "Breaches in your Maps belong to Esh\nBreaches in your Maps contain 3 additional Clasped Hands\n": 50,
    "Breaches in your Maps belong to Uul-Netol\nBreaches in your Maps contain 3 additional Clasped Hands\n": 50,
    "Breaches in your Maps belong to Chayula\nBreaches in your Maps contain 3 additional Clasped Hands\n": 50,
    "Your Maps can contain Abysses\nYour Maps contain an additional Abyss\n": 250,
    "50% increased Duration of Shrine Effects on Players in your Maps\nYour Maps contain an additional Gloom Shrine\n": 1000,
    "50% increased Duration of Shrine Effects on Players in your Maps\nYour Maps contain an additional Resonating Shrine\n": 1000,
    "Monsters Imprisoned by Essences have a 50% chance to contain a Remnant of Corruption\nYour Maps contain an additional Essence\n": 500,
    "Maps found in your Maps are Corrupted with 8 Modifiers\n": 50,
    "Create a copy of Beasts Captured in your Maps\n": 50,
    "Your Maps contain 100% increased number of Runic Monster Markers\n": 50,
    "Legion Monsters in your Maps have 100% more Life\nSplinters and Emblems dropped by Legion Monsters in your Maps are duplicated\n": 50,
    "Catalysts dropped by Metamorphs in your Maps are Duplicated\nMetamorphs in your Maps have 100% more Life\n": 50,
    "Cost of Building and Upgrading Blight Towers in your Maps is doubled\nOils found in your Maps are 1 tier higher\n": 50,
    "100% increased Intelligence gained from Immortal Syndicate targets encountered in your Maps\n": 50,
    "Delirium Reward Bars fill 100% faster in your Maps\n": 50,
    "Harvest Monsters in your Maps have 100% more Life\nHarvests in your Maps contain at least one Crop of Blue Plants\nLifeforce dropped by Harvest Monsters in your Maps is Duplicated\n": 50,
    "Harvest Monsters in your Maps have 100% more Life\nHarvests in your Maps contain at least one Crop of Purple Plants\nLifeforce dropped by Harvest Monsters in your Maps is Duplicated\n": 50,
    "Harvest Monsters in your Maps have 100% more Life\nHarvests in your Maps contain at least one Crop of Yellow Plants\nLifeforce dropped by Harvest Monsters in your Maps is Duplicated\n": 50,
    "Non-Unique Heist Contracts found in your Maps have an additional Implicit Modifier\n": 50,
    "Rerolling Favours at Ritual Altars in your Maps has no Cost the first 1 time\n": 50,
    "Harbingers in your Maps drop additional Currency Shards\nMap Bosses are accompanied by a mysterious Harbinger\nMap Bosses drop additional Currency Shards\n": 250,
    "Players gain an additional Vaal Soul on Kill\nYour Maps contain 6 additional packs of Corrupted Vaal Monsters\n": 500,
    "Items dropped by Corrupted Vaal Monsters in your Maps have 25% chance to be Corrupted\nYour Maps contain 6 additional packs of Corrupted Vaal Monsters\n": 250,
    "25% increased Beyond Demon Pack Size in your Maps\nSlaying Enemies close together can attract monsters from Beyond this realm\n": 250,
    "The First 3 Possessed Monsters drop an additional Rusted Scarab\nYour Maps contain an additional Tormented Betrayer\n": 520,
    "The First 3 Possessed Monsters drop an additional Polished Scarab\nYour Maps contain an additional Tormented Betrayer\n": 175,
    "The First 3 Possessed Monsters drop an additional Gilded Scarab\nYour Maps contain an additional Tormented Betrayer\n": 60,
    "The First 3 Possessed Monsters drop an additional Map\nYour Maps contain an additional Tormented Heretic\n": 250,
    "The First 3 Possessed Monsters drop an additional Unique Item\nYour Maps contain an additional Tormented Graverobber\n": 250,
    "Your Maps contain 6 additional packs of Corrupted Vaal Monsters\nYour Maps have a 50% chance to contain Gifts of the Red Queen per Mortal Fragment used\nYour Maps have a 50% chance to contain Gifts of the Sacrificed per Sacrifice Fragment used\n": 250,
    "Players' Vaal Skills do not apply Soul Gain Prevention\nYour Maps contain 6 additional packs of Corrupted Vaal Monsters\n": 250,
    "Your Maps contain an additional Legion Encounter\n": 250,
    "Area contains Metamorph Monsters\n": 250,
    "Your Maps contain a Blight Encounter\n": 250,
    "Your Maps contain a Mirror of Delirium\n": 100,
    "Your Maps contain The Sacred Grove\n": 100,
    "Area contains a Smuggler's Cache\n": 250,
    "Your Maps contain Ritual Altars\n": 100
}

const key2mod = {
    "Abyss": "Your Maps can contain Abysses\nYour Maps contain an additional Abyss\n",
    "Alluring": "Your Maps are Alluring\n",
    "Copy of Beasts": "Create a copy of Beasts Captured in your Maps\n",
    "Beyond": "25% increased Beyond Demon Pack Size in your Maps\nSlaying Enemies close together can attract monsters from Beyond this realm\n",
    "Blight": "Your Maps contain a Blight Encounter\n",
    "Oils Tier": "Cost of Building and Upgrading Blight Towers in your Maps is doubled\nOils found in your Maps are 1 tier higher\n",
    "Bodyguards": "An additional Map drops on Completing your Maps\nMap Bosses are accompanied by Bodyguards\n",
    "Breach": "Your Maps can contain Breaches\nYour Maps contain an additional Breach\n",
    "Xoph": "Breaches in your Maps belong to Xoph\nBreaches in your Maps contain 3 additional Clasped Hands\n",
    "Tul": "Breaches in your Maps belong to Tul\nBreaches in your Maps contain 3 additional Clasped Hands\n",
    "Esh": "Breaches in your Maps belong to Esh\nBreaches in your Maps contain 3 additional Clasped Hands\n",
    "Uul-Netol": "Breaches in your Maps belong to Uul-Netol\nBreaches in your Maps contain 3 additional Clasped Hands\n",
    "Chayula": "Breaches in your Maps belong to Chayula\nBreaches in your Maps contain 3 additional Clasped Hands\n",
    "Mirror of Delirium": "Your Maps contain a Mirror of Delirium\n",
    "Delirium Reward": "Delirium Reward Bars fill 100% faster in your Maps\n",
    "Essence": "Monsters Imprisoned by Essences have a 50% chance to contain a Remnant of Corruption\nYour Maps contain an additional Essence\n",
    "Runic Monster Markers": "Your Maps contain 100% increased number of Runic Monster Markers\n",
    "Flasks Instant": "Player's Life and Mana Recovery from Flasks are instant\nYour Maps contain 6 additional packs of Monsters that Heal\n",
    "Mysterious Harbinger": "Harbingers in your Maps drop additional Currency Shards\nMap Bosses are accompanied by a mysterious Harbinger\nMap Bosses drop additional Currency Shards\n",
    "Sacred Grove": "Your Maps contain The Sacred Grove\n",
    "Blue Plants": "Harvest Monsters in your Maps have 100% more Life\nHarvests in your Maps contain at least one Crop of Blue Plants\nLifeforce dropped by Harvest Monsters in your Maps is Duplicated\n",
    "Purple Plants": "Harvest Monsters in your Maps have 100% more Life\nHarvests in your Maps contain at least one Crop of Purple Plants\nLifeforce dropped by Harvest Monsters in your Maps is Duplicated\n",
    "Yellow Plants": "Harvest Monsters in your Maps have 100% more Life\nHarvests in your Maps contain at least one Crop of Yellow Plants\nLifeforce dropped by Harvest Monsters in your Maps is Duplicated\n",
    "Smuggler's Cache": "Area contains a Smuggler's Cache\n",
    "Contracts Implicit": "Non-Unique Heist Contracts found in your Maps have an additional Implicit Modifier\n",
    "Hunted Traitors": "Your Maps contain hunted traitors\n",
    "Legion": "Your Maps contain an additional Legion Encounter\n",
    "Splinters Emblems Duplicate": "Legion Monsters in your Maps have 100% more Life\nSplinters and Emblems dropped by Legion Monsters in your Maps are duplicated\n",
    "Magic Pack Size": "25% increased Magic Pack Size\n",
    "8 Modifiers": "Maps found in your Maps are Corrupted with 8 Modifiers\n",
    "Map 20% Quality": "Map Bosses deal 20% increased Damage\nYour Maps have 20% Quality\n",
    "Map Quality to Rarity": "Map Bosses have 20% increased Life\nQuality bonus of your Maps also applies to Rarity of Items found\n",
    "Conqueror Map": "Final Map Boss in each Map drops an additional Conqueror Map\nMap Bosses deal 100% more Damage\nMap Bosses have 200% more Life\n",
    "Elder Guardian": "Final Map Boss in each Map drops an additional Elder Guardian Map (Tier 14+)\nMap Bosses deal 100% more Damage\nMap Bosses have 200% more Life\n",
    "Shaper Guardian": "Final Map Boss in each Map drops an additional Shaper Guardian Map (Tier 14+)\nMap Bosses deal 100% more Damage\nMap Bosses have 200% more Life\n",
    "Boss Drop Unique": "Map Bosses drop 1 additional Unique Item\n",
    "Boss Drop Vaal": "Items found in your Maps have 5% chance to be Corrupted\nMap Bosses of your Corrupted Maps drop 2 additional Vaal Items\n",
    "Alva": "Your Maps contain Alva\n",
    "Einhar": "Your Maps contain Einhar\n",
    "Jun": "Your Maps contain Jun\n",
    "Niko": "Your Maps contain Niko\n",
    "Fire Monsters": "Players and Monsters take 12% increased Fire Damage\nYour Maps contain 6 additional packs of Monsters that deal Fire Damage\n",
    "Cold Monsters": "Players and Monsters take 12% increased Cold Damage\nYour Maps contain 6 additional packs of Monsters that deal Cold Damage\n",
    "Lightning Monsters": "Players and Monsters take 12% increased Lightning Damage\nYour Maps contain 6 additional packs of Monsters that deal Lightning Damage\n",
    "Physical Monsters": "Players and Monsters take 12% increased Physical Damage\nYour Maps contain 6 additional packs of Monsters that deal Physical Damage\n",
    "Chaos Monsters": "Players and Monsters take 12% increased Chaos Damage\nYour Maps contain 6 additional packs of Monsters that deal Chaos Damage\n",
    "Convert Monsters": "Your Maps contain 6 additional packs of Monsters that Convert when Killed\n",
    "Metamorph": "Area contains Metamorph Monsters\n",
    "Catalysts Duplicate": "Catalysts dropped by Metamorphs in your Maps are Duplicated\nMetamorphs in your Maps have 100% more Life\n",
    "Mysterious Barrels": "Your Maps contain 25 additional Clusters of Mysterious Barrels\n",
    "Reflected": "Players and their Minions cannot take Reflected Damage\nYour Maps contain 4 additional Packs with Mirrored Rare Monsters\n",
    "Unidentified Map": "20% increased Pack Size in your Unidentified Maps\nItems found in your Identified Maps are Identified\n",
    "Rare Map Rare Packs": "Your Magic Maps contain 4 additional packs of Magic Monsters\nYour Normal Maps contain 4 additional packs of Normal Monsters\nYour Rare Maps contain 4 additional Rare Monster packs\n",
    "Ritual Altars": "Your Maps contain Ritual Altars\n",
    "Ritual Rerolling": "Rerolling Favours at Ritual Altars in your Maps has no Cost the first 1 time\n",
    "Rogue Exiles": "Rogue Exiles deal 20% increased Damage\nRogue Exiles drop 2 additional Jewels\nRogue Exiles in your Maps have 20% increased Life\nYour Maps are inhabited by 2 additional Rogue Exiles\n",
    "Gloom Shrine": "50% increased Duration of Shrine Effects on Players in your Maps\nYour Maps contain an additional Gloom Shrine\n",
    "Resonating Shrine": "50% increased Duration of Shrine Effects on Players in your Maps\nYour Maps contain an additional Resonating Shrine\n",
    "Strongbox Enraged": "Strongbox Monsters are Enraged\nStrongbox Monsters have 500% increased Item Quantity\nYour Maps contain an additional Strongbox\n",
    "Strongbox Corrupted": "Strongboxes in your Maps are at least Rare\nStrongboxes in your Maps are Corrupted\nYour Maps contain 2 additional Strongboxes\n",
    "Syndicate Intelligence": "100% increased Intelligence gained from Immortal Syndicate targets encountered in your Maps\n",
    "Rusted Scarab": "The First 3 Possessed Monsters drop an additional Rusted Scarab\nYour Maps contain an additional Tormented Betrayer\n",
    "Polished Scarab": "The First 3 Possessed Monsters drop an additional Polished Scarab\nYour Maps contain an additional Tormented Betrayer\n",
    "Gilded Scarab": "The First 3 Possessed Monsters drop an additional Gilded Scarab\nYour Maps contain an additional Tormented Betrayer\n",
    "Tormented Heretic": "The First 3 Possessed Monsters drop an additional Map\nYour Maps contain an additional Tormented Heretic\n",
    "Tormented Graverobber": "The First 3 Possessed Monsters drop an additional Unique Item\nYour Maps contain an additional Tormented Graverobber\n",
    "Unique Monsters Drop Corrupted": "Unique Monsters drop Corrupted Items\n",
    "Vaal Monsters Items Corrupted": "Items dropped by Corrupted Vaal Monsters in your Maps have 25% chance to be Corrupted\nYour Maps contain 6 additional packs of Corrupted Vaal Monsters\n",
    "Mortal/Sacrifice Fragment": "Your Maps contain 6 additional packs of Corrupted Vaal Monsters\nYour Maps have a 50% chance to contain Gifts of the Red Queen per Mortal Fragment used\nYour Maps have a 50% chance to contain Gifts of the Sacrificed per Sacrifice Fragment used\n",
    "Soul Gain Prevention": "Players' Vaal Skills do not apply Soul Gain Prevention\nYour Maps contain 6 additional packs of Corrupted Vaal Monsters\n",
    "Vaal Soul On Kill": "Players gain an additional Vaal Soul on Kill\nYour Maps contain 6 additional packs of Corrupted Vaal Monsters\n"
}

const mod2key = {
    "Your Maps can contain Abysses\nYour Maps contain an additional Abyss\n": "Abyss",
    "Your Maps are Alluring\n": "Alluring",
    "Create a copy of Beasts Captured in your Maps\n": "Copy of Beasts",
    "25% increased Beyond Demon Pack Size in your Maps\nSlaying Enemies close together can attract monsters from Beyond this realm\n": "Beyond",
    "Your Maps contain a Blight Encounter\n": "Blight",
    "Cost of Building and Upgrading Blight Towers in your Maps is doubled\nOils found in your Maps are 1 tier higher\n": "Oils Tier",
    "An additional Map drops on Completing your Maps\nMap Bosses are accompanied by Bodyguards\n": "Bodyguards",
    "Your Maps can contain Breaches\nYour Maps contain an additional Breach\n": "Breach",
    "Breaches in your Maps belong to Xoph\nBreaches in your Maps contain 3 additional Clasped Hands\n": "Xoph",
    "Breaches in your Maps belong to Tul\nBreaches in your Maps contain 3 additional Clasped Hands\n": "Tul",
    "Breaches in your Maps belong to Esh\nBreaches in your Maps contain 3 additional Clasped Hands\n": "Esh",
    "Breaches in your Maps belong to Uul-Netol\nBreaches in your Maps contain 3 additional Clasped Hands\n": "Uul-Netol",
    "Breaches in your Maps belong to Chayula\nBreaches in your Maps contain 3 additional Clasped Hands\n": "Chayula",
    "Your Maps contain a Mirror of Delirium\n": "Mirror of Delirium",
    "Delirium Reward Bars fill 100% faster in your Maps\n": "Delirium Reward",
    "Monsters Imprisoned by Essences have a 50% chance to contain a Remnant of Corruption\nYour Maps contain an additional Essence\n": "Essence",
    "Your Maps contain 100% increased number of Runic Monster Markers\n": "Runic Monster Markers",
    "Player's Life and Mana Recovery from Flasks are instant\nYour Maps contain 6 additional packs of Monsters that Heal\n": "Flasks Instant",
    "Harbingers in your Maps drop additional Currency Shards\nMap Bosses are accompanied by a mysterious Harbinger\nMap Bosses drop additional Currency Shards\n": "Mysterious Harbinger",
    "Your Maps contain The Sacred Grove\n": "Sacred Grove",
    "Harvest Monsters in your Maps have 100% more Life\nHarvests in your Maps contain at least one Crop of Blue Plants\nLifeforce dropped by Harvest Monsters in your Maps is Duplicated\n": "Blue Plants",
    "Harvest Monsters in your Maps have 100% more Life\nHarvests in your Maps contain at least one Crop of Purple Plants\nLifeforce dropped by Harvest Monsters in your Maps is Duplicated\n": "Purple Plants",
    "Harvest Monsters in your Maps have 100% more Life\nHarvests in your Maps contain at least one Crop of Yellow Plants\nLifeforce dropped by Harvest Monsters in your Maps is Duplicated\n": "Yellow Plants",
    "Area contains a Smuggler's Cache\n": "Smuggler's Cache",
    "Non-Unique Heist Contracts found in your Maps have an additional Implicit Modifier\n": "Contracts Implicit",
    "Your Maps contain hunted traitors\n": "Hunted Traitors",
    "Your Maps contain an additional Legion Encounter\n": "Legion",
    "Legion Monsters in your Maps have 100% more Life\nSplinters and Emblems dropped by Legion Monsters in your Maps are duplicated\n": "Splinters Emblems Duplicate",
    "25% increased Magic Pack Size\n": "Magic Pack Size",
    "Maps found in your Maps are Corrupted with 8 Modifiers\n": "8 Modifiers",
    "Map Bosses deal 20% increased Damage\nYour Maps have 20% Quality\n": "Map 20% Quality",
    "Map Bosses have 20% increased Life\nQuality bonus of your Maps also applies to Rarity of Items found\n": "Map Quality to Rarity",
    "Final Map Boss in each Map drops an additional Conqueror Map\nMap Bosses deal 100% more Damage\nMap Bosses have 200% more Life\n": "Conqueror Map",
    "Final Map Boss in each Map drops an additional Elder Guardian Map (Tier 14+)\nMap Bosses deal 100% more Damage\nMap Bosses have 200% more Life\n": "Elder Guardian",
    "Final Map Boss in each Map drops an additional Shaper Guardian Map (Tier 14+)\nMap Bosses deal 100% more Damage\nMap Bosses have 200% more Life\n": "Shaper Guardian",
    "Map Bosses drop 1 additional Unique Item\n": "Boss Drop Unique",
    "Items found in your Maps have 5% chance to be Corrupted\nMap Bosses of your Corrupted Maps drop 2 additional Vaal Items\n": "Boss Drop Vaal",
    "Your Maps contain Alva\n": "Alva",
    "Your Maps contain Einhar\n": "Einhar",
    "Your Maps contain Jun\n": "Jun",
    "Your Maps contain Niko\n": "Niko",
    "Players and Monsters take 12% increased Fire Damage\nYour Maps contain 6 additional packs of Monsters that deal Fire Damage\n": "Fire Monsters",
    "Players and Monsters take 12% increased Cold Damage\nYour Maps contain 6 additional packs of Monsters that deal Cold Damage\n": "Cold Monsters",
    "Players and Monsters take 12% increased Lightning Damage\nYour Maps contain 6 additional packs of Monsters that deal Lightning Damage\n": "Lightning Monsters",
    "Players and Monsters take 12% increased Physical Damage\nYour Maps contain 6 additional packs of Monsters that deal Physical Damage\n": "Physical Monsters",
    "Players and Monsters take 12% increased Chaos Damage\nYour Maps contain 6 additional packs of Monsters that deal Chaos Damage\n": "Chaos Monsters",
    "Your Maps contain 6 additional packs of Monsters that Convert when Killed\n": "Convert Monsters",
    "Area contains Metamorph Monsters\n": "Metamorph",
    "Catalysts dropped by Metamorphs in your Maps are Duplicated\nMetamorphs in your Maps have 100% more Life\n": "Catalysts Duplicate",
    "Your Maps contain 25 additional Clusters of Mysterious Barrels\n": "Mysterious Barrels",
    "Players and their Minions cannot take Reflected Damage\nYour Maps contain 4 additional Packs with Mirrored Rare Monsters\n": "Reflected",
    "20% increased Pack Size in your Unidentified Maps\nItems found in your Identified Maps are Identified\n": "Unidentified Map",
    "Your Magic Maps contain 4 additional packs of Magic Monsters\nYour Normal Maps contain 4 additional packs of Normal Monsters\nYour Rare Maps contain 4 additional Rare Monster packs\n": "Rare Map Rare Packs",
    "Your Maps contain Ritual Altars\n": "Ritual Altars",
    "Rerolling Favours at Ritual Altars in your Maps has no Cost the first 1 time\n": "Ritual Rerolling",
    "Rogue Exiles deal 20% increased Damage\nRogue Exiles drop 2 additional Jewels\nRogue Exiles in your Maps have 20% increased Life\nYour Maps are inhabited by 2 additional Rogue Exiles\n": "Rogue Exiles",
    "50% increased Duration of Shrine Effects on Players in your Maps\nYour Maps contain an additional Gloom Shrine\n": "Gloom Shrine",
    "50% increased Duration of Shrine Effects on Players in your Maps\nYour Maps contain an additional Resonating Shrine\n": "Resonating Shrine",
    "Strongbox Monsters are Enraged\nStrongbox Monsters have 500% increased Item Quantity\nYour Maps contain an additional Strongbox\n": "Strongbox Enraged",
    "Strongboxes in your Maps are at least Rare\nStrongboxes in your Maps are Corrupted\nYour Maps contain 2 additional Strongboxes\n": "Strongbox Corrupted",
    "100% increased Intelligence gained from Immortal Syndicate targets encountered in your Maps\n": "Syndicate Intelligence",
    "The First 3 Possessed Monsters drop an additional Rusted Scarab\nYour Maps contain an additional Tormented Betrayer\n": "Rusted Scarab",
    "The First 3 Possessed Monsters drop an additional Polished Scarab\nYour Maps contain an additional Tormented Betrayer\n": "Polished Scarab",
    "The First 3 Possessed Monsters drop an additional Gilded Scarab\nYour Maps contain an additional Tormented Betrayer\n": "Gilded Scarab",
    "The First 3 Possessed Monsters drop an additional Map\nYour Maps contain an additional Tormented Heretic\n": "Tormented Heretic",
    "The First 3 Possessed Monsters drop an additional Unique Item\nYour Maps contain an additional Tormented Graverobber\n": "Tormented Graverobber",
    "Unique Monsters drop Corrupted Items\n": "Unique Monsters Drop Corrupted",
    "Items dropped by Corrupted Vaal Monsters in your Maps have 25% chance to be Corrupted\nYour Maps contain 6 additional packs of Corrupted Vaal Monsters\n": "Vaal Monsters Items Corrupted",
    "Your Maps contain 6 additional packs of Corrupted Vaal Monsters\nYour Maps have a 50% chance to contain Gifts of the Red Queen per Mortal Fragment used\nYour Maps have a 50% chance to contain Gifts of the Sacrificed per Sacrifice Fragment used\n": "Mortal/Sacrifice Fragment",
    "Players' Vaal Skills do not apply Soul Gain Prevention\nYour Maps contain 6 additional packs of Corrupted Vaal Monsters\n": "Soul Gain Prevention",
    "Players gain an additional Vaal Soul on Kill\nYour Maps contain 6 additional packs of Corrupted Vaal Monsters": "Vaal Soul On Kill"
}

export default {
    mod2weight: mod2weight,
    key2mod: key2mod,
    mod2key: mod2key
}